# Generated by Django 5.2.17 on 2026-09-20 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('mode', models.CharField(choices=[('vector', 'Vector'), ('hybrid', 'Hybrid'), ('hybrid_rerank', 'Hybrid rerank')], max_length=20)),
                ('retrieved', models.JSONField(default=list)),
                ('answer', models.TextField(blank=True)),
                ('citations', models.JSONField(default=list)),
                ('refused', models.BooleanField(default=False)),
                ('latency_ms', models.JSONField(default=dict)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documind_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
