# Generated by Django 5.2.17 on 2026-09-20 16:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('doc_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('doc_version', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=1000)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['content_hash'], name='documents_content_hash_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_path', 'doc_version'), name='documents_unique_source_version')],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_path', models.TextField()),
                ('anchor', models.CharField(max_length=500)),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunks_embedding_hnsw_idx', opclasses=('vector_cosine_ops',)), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunks_search_vector_gin_idx'), models.Index(fields=['content_hash'], name='chunks_content_hash_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'ordinal'), name='chunks_unique_document_ordinal')],
            },
        ),
    ]
